Adding Precision to set-type directive
cdapio/cdap-ui pull request #1123
Opened 2023-10-13 07:41 UTC by minurajeeve

Adding Precision text box in set-type directive and modifying directive format to include precision and adding corresponding test cases

## PR Type
- [ ] Bug Fix
- [ ] Feature

## Links
Jira: [Jira issue #](fill-in.org)

## Test Plan

## Screenshots
![image](https://github.com/cdapio/cdap-ui/assets/49074485/52559af1-5f32-410f-9c5b-3052989e9883)

2023-10-13 08:00 UTC, GnsP requested changes

2023-10-13 08:00 UTC, GnsP commented on app/cdap/components/DataPrep/Directives/ChangeDataType/DecimalOptions.tsx
> +    }
prefer template literals over string concatenation with `+` operator

2023-10-13 08:01 UTC, GnsP commented
PR type should be `feature` and JIRA issue should be specified.

2023-10-13 09:14 UTC, minurajeeve commented on app/cdap/components/DataPrep/Directives/ChangeDataType/DecimalOptions.tsx
> +    }
done

2023-10-16 09:30 UTC, minurajeeve commented
> PR type should be `feature` and JIRA issue should be specified.

Done

2023-11-20 09:46 UTC, GnsP approved these changes

2023-11-21 05:15 UTC, radhikav1 approved these changes

2023-11-21 08:30 UTC, merged