Add missing data-testids in control center page
cdapio/cdap-ui pull request #1189
Opened 2024-03-19 06:50 UTC by GnsP

# Add missing data-testids in the control center page.

## Description
Add missing data-testids in the control center page as reported by the test team.

## PR Type
- [ ] Bug Fix
- [ ] Feature
- [ ] Build Fix
- [ ] Testing
- [x] General Improvement
- [ ] Cherry Pick

## Links
Jira: [Jira issue #](fill-in.org)

## Test Plan
NA

## Screenshots
NA

2024-03-27 19:15 UTC, njbriggs approved these changes

2024-03-28 05:25 UTC, radhikav1 approved these changes

2024-03-28 05:59 UTC, radhikav1 requested changes

2024-03-28 05:59 UTC, radhikav1 commented on app/cdap/components/EntityCard/FastActions/index.js
> +const TESTID_PREFIX = 'features.entityListView.entity.fastActions';
I see that the datatestid.yaml changes are missing in this PR. Can you please check?

2024-03-28 10:50 UTC, radhikav1 approved these changes

2024-03-28 10:50 UTC, radhikav1 commented on app/cdap/components/EntityCard/FastActions/index.js
> +const TESTID_PREFIX = 'features.entityListView.entity.fastActions';
Changes are there in the yaml files, probably got merged with other PR. Ignore my previous comment

2024-03-29 02:59 UTC, GnsP commented
@radhikav1 I rebased this branch after merging https://github.com/cdapio/cdap-ui/pull/1187 . At this point the yaml file is already merged to develop. That's why it does not show up in the diff.

2024-03-29 03:00 UTC, merged