Feature/create new tethering req
cdapio/cdap-ui pull request #304
Opened 2022-01-11 06:37 UTC by mrahanjam

# Create New Tethering Request

## Description
This PR adds the functionality of creating a new tethering request to the tethering tab. Note that the `Omni Namespaces` section of the new request page is not finalized since the backend service that provides the info for it is not available yet. As an interim solution, user will input the required data.

## PR Type
- [ ] Bug Fix
- [X] Feature
- [ ] Build Fix
- [ ] Testing
- [ ] General Improvement

## Links
Jira: [Jira issue #](fill-in.org)

## Test Plan

## Screenshots

![Screen Shot 2022-01-10 at 10 36 53 PM](https://user-images.githubusercontent.com/94018249/148893328-cf44fa6a-0ca9-4788-a5c6-18f438187b4f.png)

2022-01-12 01:31 UTC, mrahanjam commented on app/cdap/components/AbstractWidget/index.tsx
> +  type: 'textbox',
TS kept complaining about this.

2022-01-12 01:32 UTC, mrahanjam commented on app/cdap/components/AbstractWidget/StateWrapper.js
> +    errors: PropTypes.array,
I believe this was a bug (found out about it through a console error). We define the errors as `IErrObj[]` in the parent component

2022-01-12 02:22 UTC, antony-britto commented on app/cdap/components/Administration/TetheringTabContent/NewTetheringRequest/index.tsx
> +    setNamespace('');
Series of state updates will trigger multiple re-renders i guess. You could consider moving these into a single object and update it once.

const [userState, setUserState] = useState({
  namespace: '',
  cpuLimit: '',
  ......
});

2022-01-12 02:25 UTC, antony-britto commented on app/cdap/components/Administration/TetheringTabContent/NewTetheringRequest/index.tsx
> +  const handleCloseAlert = () => {
this method is not required, you can directly pass 'resetValues' as onClose handler

2022-01-12 02:30 UTC, antony-britto commented on app/cdap/components/Administration/TetheringTabContent/OdfTetheringConnections/index.tsx
> +  box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.3);
0 instead of 0px

2022-01-12 02:32 UTC, antony-britto commented on app/cdap/components/Administration/TetheringTabContent/shared.styles.tsx
> +  box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.3);
0 instead of 0px

2022-01-12 02:33 UTC, antony-britto commented on app/cdap/components/Administration/TetheringTabContent/OdfTetheringConnections/index.tsx
> +    color: white;
var(--white)

2022-01-12 02:33 UTC, antony-britto commented on app/cdap/components/Administration/TetheringTabContent/shared.styles.tsx
> +    color: white;
var(--white)

2022-01-12 02:35 UTC, antony-britto commented on app/cdap/components/Administration/TetheringTabContent/NewTetheringRequest/OmniNamespaces.tsx
> +    <>
<></> is not required

2022-01-12 02:38 UTC, antony-britto commented on app/cdap/components/Administration/TetheringTabContent/NewTetheringRequest/Textbox.tsx
> +export default Textbox;
nit: 'Textbox' name may get confused with a generic component. If possible prefix it with the feature.

2022-01-12 04:16 UTC, seanfeld requested changes

2022-01-12 04:16 UTC, seanfeld commented on app/cdap/components/Administration/TetheringTabContent/NewTetheringRequest/index.tsx
> +  const [namespace, setNamespace] = useState('');
This should be moved to a useReducer - way too many state variables.

2022-01-12 04:16 UTC, seanfeld commented on app/cdap/components/Administration/TetheringTabContent/NewTetheringRequest/index.tsx
> +  const [namespace, setNamespace] = useState('');
also this file is rather big

2022-01-18 18:13 UTC, seanfeld approved these changes

2022-01-18 18:17 UTC, merged