[CDAP-18971] Disable musk option when data type is not VARCHAR
cdapio/cdap-ui pull request #400
Opened 2022-04-01 23:41 UTC by sumengwang

# [CDAP-18971] Disable musk option when data type is not VARCHAR

## Description
Question: Are there any other data types that should be allowed?

## PR Type
- [x] Bug Fix
- [ ] Feature
- [ ] Build Fix
- [ ] Testing
- [ ] General Improvement
- [ ] Cherry Pick

## Links
Jira: [CDAP-18971](https://cdap.atlassian.net/browse/CDAP-18971)

## Screenshots
![image](https://user-images.githubusercontent.com/98125204/161354718-3c25c79d-2bb6-4b90-8f3e-7d17b0521a47.png)

2022-04-04 20:26 UTC, seanfeld requested changes
are we sure that varchar is the only type? like are there no char, string etc?

2022-04-04 20:26 UTC, seanfeld commented on app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformAdd.tsx
> +          <MenuItem disabled onClick={handleMaskOpen}>
this should be to disabled={row.type.toLowerCase() !== 'varchar'} instead of having two different ones

2022-04-04 20:26 UTC, seanfeld commented on app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformAdd.tsx
> +          {row.type.toLowerCase() === 'varchar' && (
Same thing here - disabled={row.type.toLowerCase !== 'varchar'}

2022-04-05 22:48 UTC, sumengwang commented
> are we sure that varchar is the only type? like are there no char, string etc?

I added an exhaust list of string types. Let me know your thoughts.

2022-04-15 17:40 UTC, de-lan commented on app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/TransformAdd.tsx
> +          disabled={!javaSqlStringTypes.includes(row.type.toLowerCase())}
Could we extract out this condition check as a reusable function instead of repeat the code four times?

2022-04-19 18:05 UTC, seanzhougoogle commented
> > are we sure that varchar is the only type? like are there no char, string etc?
> 
> I added an exhaust list of string types. Let me know your thoughts.

checking source type may not be correct, because source type is depending on source plugin and JDBC implementation. And the list seems not correct, e.g. why `blob` is in the list ?

although checking target is not robust, either, but for now we have only one target

2022-04-19 18:08 UTC, de-lan commented on app/cdap/components/Replicator/Create/Content/SelectColumnsWithTransforms/index.tsx
> +    Observable.forkJoin([
👍

2022-04-19 18:08 UTC, de-lan approved these changes
LGTM

2022-04-20 01:31 UTC, seanfeld approved these changes

2022-04-20 03:44 UTC, merged