[CDAP-18952] Update tableName in tableTransformation to "schema.table" format
cdapio/cdap-ui pull request #401
Opened 2022-04-04 20:21 UTC by sumengwang

# [CDAP-18952] Update tableName in tableTransformation to "schema.table" format

## PR Type
- [x] Bug Fix
- [ ] Feature
- [ ] Build Fix
- [ ] Testing
- [ ] General Improvement
- [ ] Cherry Pick

## Links
Jira: [CDAP-18952](https://cdap.atlassian.net/browse/CDAP-18952)

## Test Plan
Invalid mask correctly shows error message

2022-04-04 20:27 UTC, seanfeld requested changes

2022-04-04 20:27 UTC, seanfeld commented on app/cdap/components/Replicator/Create/index.tsx
> +            tableName: table.schema + '.' + table.table,
shouldn't this be only when sql server?

2022-04-14 17:36 UTC, seanfeld approved these changes

2022-04-14 17:36 UTC, mrahanjam approved these changes

2022-04-14 17:40 UTC, de-lan approved these changes

2022-04-14 20:55 UTC, merged