[CDAP-19453] save pipeline configs to runtime args
cdapio/cdap-ui pull request #593
Opened 2022-08-12 23:07 UTC by sumengwang

# [CDAP-19453] save pipeline configs to runtime args

## Description
Previously when user changes the pipeline configurations and saves them, a redeployment will be called. We don't want to do this anymore since it's conflicted with the future life cycle management workflow. The plan is to save the pipeline configurations into the preference table (runtime arguments), with special key words.

## PR Type
- [ ] Bug Fix
- [x] Feature
- [ ] Build Fix
- [ ] Testing
- [ ] General Improvement
- [ ] Cherry Pick

## Links
Jira: [CDAP-19453](https://cdap.atlassian.net/browse/CDAP-19453)

## Test Plan
The ui passes data fine. Will test if pipelineRun can pick up the changes in preference table

2022-08-15 05:27 UTC, seanfeld commented on app/cdap/components/PipelineConfigurations/ConfigurationsContent/PipelineConfigTabContent/Instrumentation.js
> +      let { runtimeArgs } = PipelineConfigurationsStore.getState();
should these be consts?

2022-08-15 05:28 UTC, seanfeld approved these changes
Nit: seems like theres a lot of lets that should be consts? - other than that it looks good

2022-08-16 22:06 UTC, njbriggs commented on app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigModelessActionButtons/index.js
> +    Observable.forkJoin(updatePreferences()).subscribe(
Nit: Can remove `Observable.forkJoin()` since that was used to combine the 2 Observables

2022-08-16 22:12 UTC, njbriggs reviewed
Do there need to be similar changes on the Studio side?

2022-10-12 04:17 UTC, seanfeld commented on app/cdap/components/PipelineConfigurations/Store/ActionCreator.js
> +        payload: { keyValues },
could you combine these into one action so you dispatch once?

2022-10-12 04:18 UTC, seanfeld commented on app/cdap/components/PipelineConfigurations/Store/index.js
> +  if (currentRuntimeArgs.pairs.length >= 1 && currentRuntimeArgs.pairs[0].key !== '') {
could get rid of the `>= 1` ?

2022-10-12 04:19 UTC, seanfeld commented on app/cdap/components/PipelineDetails/PipelineDetailsTopPanel/index.tsx
> +  });
is this supposed to be }, []);?

2022-10-12 04:20 UTC, seanfeld commented on app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/RuntimeArgsPairsMaterial.tsx
> +      !this.props.showGeneratedArgs &&
put a comment in this thing

2022-10-12 04:21 UTC, seanfeld commented on app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.tsx
> + * Copyright © 2018 Cask Data, Inc.
copyright year

2022-10-12 04:22 UTC, seanfeld commented on app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.tsx
> +require('./RuntimeArgsKeyValuePairWrapper.scss');
why require over import?

2022-10-12 04:24 UTC, seanfeld commented on app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.tsx
> +    .map((pair) => pair.key)
why do you need this map?

2022-10-12 04:25 UTC, seanfeld commented on app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.tsx
> +    if (typeof onRuntimeArgsChange === 'function') {
....?

2022-10-12 04:25 UTC, seanfeld commented on app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.tsx
> +          <IconSVG name={showGeneratedArgs ? 'icon-caret-down' : 'icon-caret-right'} />
is this all copied code? don't use IconSVG

2022-10-12 04:26 UTC, seanfeld commented on app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.tsx
> +        <a
This should be an icon button?

2022-10-12 04:27 UTC, seanfeld commented on app/cdap/components/PipelineDetails/PipelineRuntimeArgsDropdownBtn/RuntimeArgsKeyValuePairWrapper/index.tsx
> +          <span className="float-right num-rows">
is this new stuff? if not why so many classnames

2022-10-12 04:34 UTC, seanfeld requested changes
left comments - err check feedback

2022-10-13 18:09 UTC, seanfeld commented on app/cdap/components/PipelineConfigurations/ConfigurationsContent/ConfigModelessActionButtons/index.tsx
> +export const ConfigModelessActionButtons = ({ ...props }: IConfigModelessActionButtonsProps) => {
why are you spreading props?

2022-10-13 18:14 UTC, seanfeld approved these changes

2022-10-13 18:18 UTC, de-lan approved these changes

2022-10-13 18:37 UTC, merged