Clientpr/import schema
cdapio/cdap-ui pull request #755
Opened 2022-11-09 13:51 UTC by sivaRajanaDivami

# TITLE

## Description
Summary of changes

## PR Type
- [ ] Bug Fix
- [ ] Feature
- [ ] Build Fix
- [ ] Testing
- [ ] General Improvement
- [ ] Cherry Pick

## Links
Jira: [Jira issue #](fill-in.org)

## Test Plan

## Screenshots

2022-11-10 13:20 UTC, tharunpola requested changes

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ConnectionList/Components/ConnectionTabs/index.tsx
> +  if (index === 0) {
convert it to index === 0 && (DataPrepStore......)

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/GridTable/index.tsx
> +  const [invalidCount, setInvalidCount] = useState<IInvalidCount[]>([
rename it to [invalidDataCount, setInvalidDataCount]

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ParsingDrawer/Components/InputSelect/index.tsx
> +      {Array.isArray(options) &&
options type as an array is already defined in the interface, and Array.isArray(options) is not needed

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ParsingDrawer/Components/ParsingHeaderActionTemplate/__test__/ParsingHeaderActionTemplate.test.tsx
> +import ParsingHeaderActionTemplate from '..';
please add full path

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ParsingDrawer/Components/ParsingHeaderActionTemplate/index.tsx
> +        style={{ display: 'none' }}
please remove inline styles

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ParsingDrawer/Components/ParsingPopupBody/index.tsx
> +    selectedFormatValue = FORMAT_OPTIONS?.filter((i) => i.value === format);
replace i with eachOption

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ParsingDrawer/Components/ParsingPopupBody/parsingOptions.ts
> +    value: T.translate(`${PREFIX}.utf8`),
the label can be stored in text-en.yaml
but values are just constants and it is unnecessary to be placed in text-en.yaml file

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ParsingDrawer/index.tsx
> +import ParsingPopupBody from './Components/ParsingPopupBody';
update it to the full path

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ParsingDrawer/index.tsx
> +} from './defaultValues';
update it to the full path

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ParsingDrawer/index.tsx
> +import { useStyles } from './styles';
update it to the full path

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ParsingDrawer/index.tsx
> +  const [drawerStatus, setDrawerStatus] = useState(true);
define types to all useStates if possible

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/ParsingDrawer/index.tsx
> +    if (failureSchema && toaster.lastValue !== 'fail') {
remove nested if else

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/SnackbarComponent/Components/TransitionComponent/index.tsx
> +import { ITransitionComponentProps } from './types';
add full import path

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/SnackbarComponent/Components/TransitionComponent/index.tsx
> +        &nbsp;Error
remove &nbsp and try to add padding and margin

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/SnackbarComponent/Components/TransitionComponent/styles.ts
>      color: '#E97567',
check if colors are available in MUI color pallet

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/SnackbarComponent/index.tsx
> +import { IPositionedSnackbarProps } from './types';
add full import path

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/SnackbarComponent/index.tsx
> +          close={() => handleClose()}
replace above line with close={ handleClose}

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/components/SnackbarComponent/styles.ts
> +    height: '148px',
convert px to numbers all over the file

2022-11-10 13:20 UTC, tharunpola commented on app/cdap/text/text-en.yaml
>        success: You have successfully created the pipeline "{pipelineName}".
check all the new changes in alphabetical order

2022-11-11 05:56 UTC, dlakshmi123 commented on app/cdap/components/GridTable/index.tsx
> +  const [invalidCount, setInvalidCount] = useState<IInvalidCount[]>([
done

2022-11-11 06:54 UTC, dlakshmi123 commented on app/cdap/components/ParsingDrawer/Components/InputSelect/index.tsx
> +      {Array.isArray(options) &&
done

2022-11-11 06:57 UTC, dlakshmi123 commented on app/cdap/components/ParsingDrawer/Components/ParsingHeaderActionTemplate/__test__/ParsingHeaderActionTemplate.test.tsx
> +import ParsingHeaderActionTemplate from '..';
done

2022-11-11 07:04 UTC, dlakshmi123 commented on app/cdap/components/ParsingDrawer/Components/ParsingHeaderActionTemplate/index.tsx
> +        style={{ display: 'none' }}
done

2022-11-11 07:06 UTC, dlakshmi123 commented on app/cdap/components/ParsingDrawer/Components/ParsingPopupBody/index.tsx
> +    selectedFormatValue = FORMAT_OPTIONS?.filter((i) => i.value === format);
done

2022-11-11 07:08 UTC, dlakshmi123 commented on app/cdap/components/ParsingDrawer/index.tsx
> +import ParsingPopupBody from './Components/ParsingPopupBody';
done

2022-11-11 07:10 UTC, dlakshmi123 commented on app/cdap/components/ParsingDrawer/index.tsx
> +} from './defaultValues';
done

2022-11-11 07:12 UTC, dlakshmi123 commented on app/cdap/components/ParsingDrawer/index.tsx
> +import { useStyles } from './styles';
done

2022-11-11 11:50 UTC, dlakshmi123 commented on app/cdap/components/ParsingDrawer/Components/ParsingPopupBody/parsingOptions.ts
> +    value: T.translate(`${PREFIX}.utf8`),
done

2022-11-11 12:23 UTC, dlakshmi123 commented on app/cdap/components/ConnectionList/Components/ConnectionTabs/index.tsx
> +  if (index === 0) {
done

2023-03-21 19:55 UTC, closed without merging