Review: CDAP 19698 Feature - File Parsing Panel
cdapio/cdap-ui pull request #776
Opened 2022-11-15 18:45 UTC by adityadivami

# TITLE
Feature - File Parsing Panel

## Description
Summary of changes
This PR includes the File parsing panel feature

## PR Type
- [ ] Bug Fix
- [ ] Feature
- [ ] Build Fix
- [ ] Testing
- [ ] General Improvement
- [ ] Cherry Pick

## Links
Jira: [Jira issue #](fill-in.org)
https://cdap.atlassian.net/browse/CDAP-19698

## Test Plan
1. FE_02_001 - Verify whether the parsing popup window is displayed or not. - Pass
2. FE_02_002 - Verify whether the "Parsing" text is displayed as the title on the popup screen or not - Pass
3. FE_02_003 - Verify the "download icon" is displayed on the right side of the pop-up screen - Pass
4. FE_02_004 - Verify the "Import schema" text is displayed in between the download icon & close icon of the pop-up screen - Pass
5. FE_02_005 - Verify the "close icon" is displayed on the right end of the pop-up screen - Pass
6. FE_02_006 - Verify by clicking on the 'Close icon' and check pop screen is closing or not - Pass
7. FE_02_007 - Verify the action after clicking on the 'Close icon'. - Pass
8. FE_02_008 - Verify whether the format field dropdown list fields are displayed or not. - Pass
9. FE_02_009 - Verify whether the Encoding drop-down list fields are displaying or not. - Pass
10. FE_02_010 - Verify by changing the selection of 'the "Format & Encoding" drop-down list fields. - Pass
11. FE_02_011 - Verify the Enable Quoted Value checkbox and check the user is able to check/uncheck the box - Pass
12. FE_02_012 - Verify the Use First Row as Header checkbox and check the user is able to check/uncheck the box - Pass
13. FE_02_013 - Verify after selecting the Use First Row as Header checkbox and verify the data interchanging. - Pass
14. FE_02_014 - Verify the info icon beside once applied parsing settings cannot be changed. displayed or not. - Pass
15. FE_02_015 - Verify the 'Apply' Text button by mouse hovering - Pass
16. FE_02_016 - Verify by clicking on the 'Apply' button  - Pass
17. FE_02_017 - Verify the redirection after clicking on the 'Apply' button. - Pass
18. FE_02_018 - Verify after the 'Apply' button whether the popup message is displayed with a valid/successful submission message or not. - Pass
19. FE_02_019 - Verify after the 'Apply' button whether the popup message is displayed with an invalid/warning message or not. - Pass

## Screenshots
<img width="562" alt="Screenshot 2022-11-16 at 12 12 32 AM" src="https://user-images.githubusercontent.com/61772422/202000243-bbfdbeb9-c345-438d-b045-ebf2622ab226.png">
<img width="570" alt="Screenshot 2022-11-16 at 12 12 38 AM" src="https://user-images.githubusercontent.com/61772422/202000265-bb1db57d-fd26-4a54-9bf8-3aec8a6724f2.png">
<img width="1425" alt="Screenshot 2022-11-16 at 12 12 50 AM" src="https://user-images.githubusercontent.com/61772422/202000271-47e400b2-ddf5-498f-8c37-8d76f8eb2405.png">
<img width="1438" alt="Screenshot 2022-11-16 at 12 13 01 AM" src="https://user-images.githubusercontent.com/61772422/202000283-9fac9dd3-0e93-4bdc-acba-973a498010c3.png">

2022-11-17 03:30 UTC, seanfeld requested changes
Please start adding which files need to be skipped - also in the screenshot it looks like the incorrect font is used in the dropdowns

2022-11-21 07:22 UTC, adityadivami commented
> Please start adding which files need to be skipped - also in the screenshot it looks like the incorrect font is used in the dropdowns

All files are to be reviewed as part of this PR

2022-11-28 22:30 UTC, njbriggs commented on app/cdap/components/GridTable/index.tsx
> +  const [isFirstWrangle, setIsFirstWrangle] = useState<boolean>(false);
Please add some comments about what `isFirstWrangle` means

2022-11-28 22:40 UTC, njbriggs commented on app/cdap/components/ParsingDrawer/Components/ParsingPopupBody/index.tsx
> +      <CheckBox
These fields should not be hardcoded. Please look at how the current parsing dialog handles different file types.

2022-11-28 22:44 UTC, njbriggs commented on app/cdap/components/ParsingDrawer/Components/ParsingPopupBody/parsingOptions.ts
> +export const CHAR_ENCODING_OPTIONS = [
These are provided by the API and should not be hardcoded.

2023-03-21 19:52 UTC, closed without merging